name = "MyHW"
uuid = "8c799925-b97e-4f58-b32c-e4cb04ec3d2a"
authors = ["Ekaterina Tatarnikova <Ekaterina.Tatarnikova@student.uibk.ac.at>"]
version = "0.1.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
